/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module counter_2 (
    input clk,
    input rst,
    input reset_flag,
    input button,
    output reg flagout
  );
  
  
  
  wire [1-1:0] M_edge_detector_out;
  reg [1-1:0] M_edge_detector_in;
  edge_detector_11 edge_detector (
    .clk(clk),
    .in(M_edge_detector_in),
    .out(M_edge_detector_out)
  );
  wire [1-1:0] M_button_cond_out;
  reg [1-1:0] M_button_cond_in;
  button_conditioner_12 button_cond (
    .clk(clk),
    .in(M_button_cond_in),
    .out(M_button_cond_out)
  );
  reg [0:0] M_flag_d, M_flag_q = 1'h0;
  
  always @* begin
    M_flag_d = M_flag_q;
    
    M_button_cond_in = button;
    M_edge_detector_in = M_button_cond_out;
    if (M_edge_detector_out) begin
      M_flag_d = 1'h1;
    end
    if (reset_flag) begin
      M_flag_d = 1'h0;
    end
    flagout = M_flag_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_flag_q <= 1'h0;
    end else begin
      M_flag_q <= M_flag_d;
    end
  end
  
endmodule
